# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='national_id',
            new_name='nationalId',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
    ]
