# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20161229_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='picture',
            field=models.ImageField(null=True, upload_to='media/user_picture'),
        ),
    ]
