# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='picture',
            field=models.ImageField(upload_to='media/user_picture'),
        ),
    ]
