# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 06:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalID', models.CharField(max_length=10, unique=True)),
                ('visitDuration', models.IntegerField(default=1, null=True)),
                ('contractFile', models.FileField(null=True, upload_to='media/user_contract')),
                ('resume', models.FileField(null=True, upload_to='media/user_resume')),
                ('picture', models.ImageField(null=True, upload_to='media/user_picture')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=200)),
                ('endOfGraduate', models.CharField(max_length=200)),
                ('degree', models.CharField(choices=[('GL', 'عمومی'), ('MO', 'متخصص'), ('FT', 'فوق تخصص'), ('JR', 'جراح')], default='GL', max_length=2)),
                ('degreeTitle', models.CharField(choices=[('aa', 'داخلی و غدد'), ('ab', 'عمومی'), ('ac', 'اورولوژی'), ('ad', 'زنان'), ('ae', 'گوارش')], default='aa', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='VisitPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashAmount', models.FloatField(default=0)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VisitTimeInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('status', models.BooleanField(default=False)),
                ('dailyTimeTable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.DailyTimeTable')),
            ],
        ),
        migrations.CreateModel(
            name='VisitTimeIntervalMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('checked', models.BooleanField(default=False)),
                ('isDone', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
                ('visitTimeInterval', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.VisitTimeInterval')),
            ],
        ),
        migrations.AddField(
            model_name='visitpayment',
            name='visitTimeIntervalMap',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.VisitTimeIntervalMap'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctorDegree',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.DoctorDegree'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='office',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.Office'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailytimetable',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor'),
        ),
    ]
