# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='office',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.Office'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='visitDuration',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
    ]
