# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visittimeinterval',
            name='status',
        ),
        migrations.AddField(
            model_name='visittimeintervalmap',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
