# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20170108_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='visittimeinterval',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
