# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20161229_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='nationalID',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
