# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20170219_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('numOfrate', models.IntegerField(default=0)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor')),
            ],
        ),
    ]
