# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_patientrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientrate',
            old_name='numOfrate',
            new_name='numOfRate',
        ),
        migrations.AddField(
            model_name='patientrate',
            name='totalRate',
            field=models.IntegerField(default=0),
        ),
    ]
