# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20161229_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='picture',
            field=models.ImageField(null=True, upload_to='media/user_picture'),
        ),
    ]
