# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_doctor_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='visitDuration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
