# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_auto_20170219_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientrate',
            old_name='rate',
            new_name='lastRate',
        ),
        migrations.RemoveField(
            model_name='patientrate',
            name='numOfRate',
        ),
    ]
