# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_auto_20161230_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='visitDuration',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
